language: php

cache:
  directories:
    - bin
    - vendor
    - $HOME/.composer/cache
    - $HOME/.mink-log-cache

php:
  - 7.0
  - 5.6
  - 5.5
  - hhvm

before_install:
  - mkdir -p $HOME/.mink-log-cache
  - travis/run-selenium

before_script:
  - composer install --prefer-source
  - travis/tools/wait-for-port 4444

script:
  - bin/phpspec run -f pretty
  - bin/behat --strict -f progress
